rpc_server:
  host: 0.0.0.0
  port: 8289
http_server:
  host: 0.0.0.0
  port: 8188

chains:
  - chain_name: "Bitcoin"
    chain_id: "DappLinkBitcoin"
    netword: mainnet
  - chain_name: "Ethereum"
    chain_id: "DappLinkEthereum"
    netword: mainnet
  - chain_name: "Solana"
    chain_id: "DappLinkSolana"
    netword: mainnet
  - chain_name: "Tron"
    chain_id: "DappLinkTron"
    netword: mainnet

wallet_node:
  eth:
    rpc_url: 'https://eth.drpc.org'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://api-holesky.etherscan.io/api?'
    data_api_key: 'HZEZGEPJJDA633N421AYW9NE8JFNZZC7JT'
    data_api_token: ''
    time_out: 15

  btc:
    rpc_url: 'bitcoin-mainnet.core.chainstack.com'
    rpc_user: 'objective-colden'
    rpc_pass: 'plank-scored-lying-duty-lazily-smudge'
    data_api_url: 'https://www.oklink.com/'
    data_api_key: '5181d535-b68f-41cf-bbc6-25905e46b6a6'
    data_api_token: ''
    time_out: 100
    tp_api_url: 'https://blockchain.info/'

network: mainnet
enable_api_cache: false


